### ISSUE TITLE
Build failure on Raspbian Jessie

### ISSUE THREAD

**Issue by uzadow** [libavg/libavg#729]
```
In file included from AudioDecoderThread.cpp:24:0:
AudioDecoderThread.h:74:9: error: 'ReSampleContext' does not name a type
         ReSampleContext * m_pResampleContext;
         ^
```

Probably related to newer ffmpeg version.

**Comment by hellbender3069** [comment]
Hi Uli,
go back to the line you reverted from my patch. It seems one platform actually has the define set as you programmed it, but other platforms don't set this flag. I added my patch as a seperate #if statement this time on my pi to make it build on the pi.

**Comment by uzadow** [comment]
Found an ifdef that works on all versions I can get my hands on :-).

**Comment by uzadow** [comment]
Reopened because the fix breaks Ubuntu 12.04.

**Comment by uzadow** [comment]
I've added a branch for PI development: feature/raspi_jessie

https://github.com/libavg/libavg/tree/feature/raspi_jessie.

**Comment by hellbender3069** [comment]
Ok Nice,I will start using this one. One problem I had with using your guide on the website was a conflict with libjpeg8-dev, since libtiff55-dev is dependent on libjpeg-dev. but libjpeg-dev is dependend on libjpeg62-dev. So we have a bit of a loop there. I am currently in the middle of updating the image to the latest clean version of jesse and restart to see if all instructions can be followed.
I'll keep you informed.
Greetz,Michel

Date: Mon, 1 Feb 2016 13:34:25 -0800

**Comment by uzadow** [comment]
I believe libjpeg8-dev isn't necessary, and I've updated the install docs accordingly.
Right now, all the basic tests are passing, but for some reason testI18NWords fails when trying to insert a non-breaking space.
I'm working on it.

**Comment by uzadow** [comment]
Ok, things are looking good. Fixed the text rendering bug. On the branch, Jessie runs fine now (with the minor stuff we had before: #627.

When Ubuntu 16.04 is out, we'll drop support for Ubuntu 12.04 and merge this branch into master.

**Comment by hellbender3069** [comment]
LibAVG still can't be build on jessie due to undefined symbols. 

In file included from AudioDecoderThread.cpp:24:0:
AudioDecoderThread.h:74:9: error: 'ReSampleContext' does not name a type
         ReSampleContext * m_pResampleContext;

The header file from the jessie branch still doesn't solve this issue

**Comment by scotty007** [comment]
I just compiled the feature/raspi_jessie branch on the latest raspbian (16-05-10-raspbian-jessie).
The tests (and any started app) fails to open an EGL display.
Here the `make check` output:
```
Running suite PlayerTestSuite
  Running PlayerTest
Creating window failed: Could not get EGL display. (size=[      160,      120], bpp=24).
######## PlayerTestSuite failed. ########
FAIL: testplayer
```
Is it important to use a self-built SDL2 (as described on the [RPi install page](https://www.libavg.de/site/projects/libavg/wiki/RaspberryPISourceInstall)? I just installed `libsdl2-dev` from the official repos (version 2.0.2).

**Comment by uzadow** [comment]
Exactly. SDL 2.0.2 doesn't work.

**Comment by scotty007** [comment]
All but 3 tests passed with SDL2.0.4 :-) :

```
FAIL: testCurve (VectorTest.VectorTestCase)
AssertionError:   testCurve1: Difference image has avg=0.20, std dev=7.12

FAIL: testMesh (VectorTest.VectorTestCase)
AssertionError:   testMesh4: Difference image has avg=0.27, std dev=6.94

FAIL: testCanvasMipmap (OffscreenTest.OffscreenTestCase)
AssertionError:   testCanvasMipmap: Difference image has avg=1.20, std dev=11.76
```
The first two are just minor renderer related pixel errors. The third result image shows the canvas shrunk compared to the base image.

BTW: Ubuntu 16.04 is out ;-)

**Comment by scotty007** [comment]
I merged the master branch into feature/raspi_jessie and fixed the (now) cmake based build configuation. It builds on a RPi3 with
`$ cmake -DAVG_ENABLE_EGL=TRUE -DAVG_ENABLE_RPI=TRUE ..`

All tests but the above 3 and 1 additional passed. The new one is:
```
FAIL: testPositioning (WordsTest.WordsTestCase)
AssertionError: False is not true
```

**Comment by scotty007** [comment]
Are the fixes in [WordsNode.cpp](https://github.com/libavg/libavg/compare/feature/raspi_jessie#diff-a5c3fc2fdd04525e3e534974bf2a97f5) raspi specific or can they get merged into master? If so, we could merge the raspi_jessie branch into master (losing Ubuntu 12.04 support as mentioned above).

**Comment by uzadow** [comment]
Hm, the WordsNode changes are from 027a4e3b50e9a360a261f97d1e3080c618058ba3. Doesn't look dangerous.

But: Unfortunately, we still have an important machine running 12.04 (our big wall). Maybe that's a reason to finally update it...

**Comment by scotty007** [comment]
I got the cross compiling and the [wiki page](https://www.libavg.de/site/projects/libavg/wiki/RaspberryPISourceInstall) updated. Seems to work fine so far, testers welcome ;-)

There's one strange issue left: When I run `Test.py` remote via ssh, it passes all tests (except the 4 mentioned above). When I start it right on the Pi, it passes the first (about 30) tests and then fails:
```
testSVG (PlayerTest.PlayerTestCase) ... **
GLib:ERROR:/build/glib2.0-tTvduh/glib2.0-2.42.1/./glib/gvarianttypeinfo.c:184:g_variant_type_info_check:
 assertion failed: (0 <= index && index < 24)
Aborted
```
This doesn't happen with a native build. Any hints?

**Comment by uzadow** [comment]
Hm. If it doesn't happen with the native build, it might be a difference in the compiler - either settings or compiler version. I'd try a non-optimized build to see what happens. Also, what does the callstack look like?

**Comment by scotty007** [comment]
Outdated. Rasperry Pi specific build configuration and render code has been removed, support was added to Mesa and SDL2. Building on Raspberry Pi OS just requires `cmake -DAVG_ENABLE_EGL=TRUE` now.
